/**
 * Creating a sidebar enables you to: - Create an ordered group of docs
 * - Show a sidebar in the docs site - Home page with custom docs cards
 * - Automatically generate a sidebar from folder structure
 * - order docs based on category
 * - customize the sidebar header
 *
 * To learn more, visit: https://docusaurus.io/docs/sidebar
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.',
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-page'],
    },
  ],
   */
};

module.exports = sidebars;
